name: Open a Rust release PR
on:
  workflow_dispatch:
    inputs:
      crate:
        description: Crate to release
        required: true
        type: choice
        options:
          - aligned-sized
          - light-bounded-vec
          - light-circuitlib-rs
          - light-concurrent-merkle-tree
          - light-hash-set
          - light-hasher
          - light-indexed-merkle-tree
          - light-macros
          - light-merkle-tree-event
          - light-merkle-tree-reference
          - light-registry
          - light-test-utils
          - light-utils
          - light-wasm-hasher
          - account-compression
          - light-compressed-pda
          - light-compressed-token
      version:
        description: Version to release
        required: true
        type: string

jobs:
  make-release-pr:
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: chainguard-dev/actions/setup-gitsign@main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-release
        run: |
          VERSION="$(curl --silent "https://api.github.com/repos/crate-ci/cargo-release/releases/latest" | jq -r .tag_name)"
          wget https://github.com/crate-ci/cargo-release/releases/download/"$VERSION"/cargo-release-"$VERSION"-x86_64-unknown-linux-gnu.tar.gz
          tar -xzvf cargo-release-"$VERSION"-x86_64-unknown-linux-gnu.tar.gz --wildcards '*cargo-release' --strip-components=1
          cp cargo-release "$HOME"/.cargo/bin

      - name: Bump crate version
        run: |
          cargo release version --execute --no-confirm \
            -p "${{ inputs.crate }}" "${{ inputs.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        env:
          COMMIT_MESSAGE: "chore: bump version of ${{ inputs.crate }} to ${{ inputs.version }}"
        with:
          commit-message: ${{ env.COMMIT_MESSAGE }}
          title: ${{ env.COMMIT_MESSAGE }}
          branch: "bump-${{ inputs.crate }}-to-${{ inputs.version }}"
          labels: "version bump"
