name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Auto Tag
        shell: bash
        run: |
          set -eux

          function rust_version() {
            cargo pkgid -p $1 | cut -d "@" -f2
          }

          function ts_version() {
            pnpm list --filter $1 --depth 0 --json | jq -r '.[0].version'
          }

          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          if [[ "$COMMIT_MESSAGE" == *"bump version of"* ]]; then
            PACKAGE_NAME=$(echo "$COMMIT_MESSAGE" | grep -o "bump version of [^ ]*" | cut -d " " -f4)

            if [[ -n "$PACKAGE_NAME" ]]; then
              # First try getting the Rust version.
              VERSION=$(rust_version "$PACKAGE_NAME")
              if [[ -z "$VERSION" ]]; then
                # If no version was found, try the TypeScript version.
                VERSION=$(ts_version "$PACKAGE_NAME")
              fi

              if [[ -n "$VERSION" ]]; then
                echo "Creating tag for package: $PACKAGE_NAME v$VERSION"

                NEW_TAG="v$VERSION"
                git config user.name "GitHub Actions"
                git config user.email "github-actions@github.com"
                git tag "${PACKAGE_NAME}-${NEW_TAG}"
                git push origin "${PACKAGE_NAME}-${NEW_TAG}"
              fi
            fi
          fi
